import glob
import os.path
import sys

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

# take driver name from directory name, replace if you don't like the result
libName = os.path.basename( Dir( '.' ).srcnode().abspath )

# automatically glob files
headers = globSourceFiles( '*.h' )
sources = globSourceFiles( '*.cpp' ) 
haptic_core_options = mergeOptions( utcore_all_options )
haptic_core_options ['CPPPATH'] += [ os.path.join ( getCurrentPath(), '../') ]

env.AppendUnique( **haptic_core_options )


# compile driver
libs = setupLibraryBuild(env, sources, libName, 'haptic')

haptic_core_options[ 'LIBS' ] += libs
haptic_core_options[ 'LIBPATH' ] += [ install_library_prefix ]

have_haptic_core = libs != 0

Export( 'have_haptic_core', 'haptic_core_options' )

# also create a visual studio project for the library	
createVisualStudioProject(env, sources, libName, libName)
	