import glob
import os.path
import sys

# import variables from other scons files
Import( '*' )
env = masterEnv.Clone()

# take driver name from directory name, replace if you don't like the result
driverName = 'HAPIHapticsDevice'

# automatically glob files
headers = globSourceFiles( '*.h' )
sources = globSourceFiles( '*.cpp' ) 
haptic_device_options = mergeOptions( utcore_all_options, utdataflow_all_options, h3dutil_options, pthreads_options, hapi_options, openhaptics_options)

env.AppendUnique( **haptic_device_options )


# compile driver
setupComponentBuild(env, sources, 'haptic')

# also create a visual studio project for the library	
createVisualStudioProject(env, sources, driverName, driverName)
	